<?php
/*
Plugin Name: WP 2-Stage Login
Plugin URI: http://plugins.atdeb.com/2stage-login.1.0.zip
Description: Enables 2 stage login feature for better security
Version: 1.0
Author: Debobrata
Author URI: http://www.atdeb.com/
License: GPLv2 or later
*/


/* ========================================================================
 * CONSTANTS
 * ======================================================================== */
if (!defined('PLUGIN_PREFIX')) {
    define('PLUGIN_PREFIX', 'wp2sl_');
}


/* ========================================================================
 * INCLUDES
 * ======================================================================== */
include_once 'settings/menu_settings.php';
include_once 'plugin-functions.php';
include_once 'ajax-functions.php';


/* ========================================================================
 * GLOBALS
 * ======================================================================== */
$default_gl_tpl_logo = wp2sl_url()."/images/banner-lock-icon-128.png";
$default_gl_tpl_bg = wp2sl_url()."/templates/forms/login/images/bg.jpg";


/* ========================================================================
 * Plugin Actions / Hooks
 * ======================================================================== */
register_activation_hook(__FILE__, 'wp2sl_activation');
//register_deactivation_hook(__FILE__, 'wp2sl_deactivation');

add_action('init', 'wp2sl_register_session');
add_action('init', 'wp2sl_update_page_slug');
add_action('admin_enqueue_scripts', 'wp2sl_js_include');
add_action('wp_enqueue_scripts', 'wp2sl_js_include');
add_action('admin_print_styles', 'wp2sl_css_include');
add_action('wp_print_styles', 'wp2sl_css_include');

add_action('wp2sl_enqueue_scripts', 'wp2sl_form_js_include');
add_action('wp2sl_enqueue_styles', 'wp2sl_form_css_include');

// Hook no-conflict
add_action('wp_head', 'wp2sl_add_noconflict');
add_action('admin_head', 'wp2sl_add_noconflict');
add_action('wp2sl_enqueue_scripts', 'wp2sl_add_noconflict');

if (get_option('_wp2sl_gl_active') == "yes") {
    add_action('init', 'wp2sl_redirect_login_page');
    add_action('wp_logout', 'wp2sl_logout_actions');
}


/* ========================================================================
 * Plugin Filters
 * ======================================================================== */
add_filter('page_template', 'wp2sl_tpl_assign');


/* ========================================================================
 * Plugin activation
 * ======================================================================== */
function wp2sl_activation() {
    // Create default generic login details for the user who activates the plugin
    $cuser = wp_get_current_user();
    $demo_login_usrname = 'demo';
    $demo_login_pwd = 'demo';
    if ($cuser->ID) {
        update_user_meta($cuser->ID, '_wp2sl_gl_username', $demo_login_usrname);
        update_user_meta($cuser->ID, '_wp2sl_gl_pwd', wp2sl_generate_gl_password($demo_login_pwd));
    }
    
    $wpu_list = get_users();
    if ($wpu_list) {
        foreach ($wpu_list as $u) {
            if ($u->ID != $cuser->ID) {
                if (get_option('admin_email')) {
                    $header_email = " <".get_option('admin_email').">";
                } else {
                    $header_email = "";
                }
                $headers = "From: Admin - ".get_bloginfo('name').$header_email;
    
                $subject = "Generic Login Activated - ".get_bloginfo('name');

                $msg  = "Hello User,\r\n\r\n";
                $msg .= get_bloginfo('name')." has now enabled 2-stage authentiction. This email is generated by 2-Stage Login for a generic login which has been activated for your account: {$u->user_login}. ";
                $msg .= "Please note the username and password to login through Generic Login into our website. ";
                $msg .= "If you can not login with the given credentials, then please contact website admin.";
                $msg .= "\r\n\r\nUsername: {$demo_login_usrname}";
                $msg .= "\r\nPassword: {$demo_login_pwd}";
                $msg .= "\r\n\r\n\r\nThanks!";

                @wp_mail($u->user_email, $subject, $msg, $headers);
    
                update_user_meta($u->ID, '_wp2sl_gl_username', $demo_login_usrname);
                update_user_meta($u->ID, '_wp2sl_gl_pwd', wp2sl_generate_gl_password($demo_login_pwd));
            }
        }
    }
    
    // UPDATE DEFAULT PLUGIN VALUE IN OPTION
    $default_gl_tpl_logo = wp2sl_url()."/images/banner-lock-icon-128.png";
    $default_gl_tpl_bg = wp2sl_url()."/templates/forms/login/images/bg.jpg";
    update_option('_wp2sl_gl_page_logo', $default_gl_tpl_logo);
    update_option('_wp2sl_gl_page_bg', $default_gl_tpl_bg);
    update_option('_wp2sl_glogin_form_template', 'form-1');
    
    wp2sl_add_pages();
}


/* ========================================================================
 * Plugin de-activation
 * ======================================================================== */
function wp2sl_deactivation() {
    global $wpdb;
    $username_meta_key = '_wp2sl_gl_username';
    $pwd_meta_key = '_wp2sl_gl_pwd';
    
    $sql_uname = "DELETE FROM `{$wpdb->prefix}usermeta` WHERE `meta_key` = '".$username_meta_key."'";
    $sql_pwd = "DELETE FROM `{$wpdb->prefix}usermeta` WHERE `meta_key` = '".$pwd_meta_key."'";
    
    $wpdb->query($wpdb->prepare($sql_uname));
    $wpdb->query($wpdb->prepare($sql_pwd));
}


/* ======================================================================
 * Session Handling
 * ====================================================================== */
function wp2sl_register_session() {
    if (!session_id()) {
        session_start();
    }
}


/* ========================================================================
 * Create Login page / Update options when plugin is activated
 * ======================================================================== */
function wp2sl_add_pages() {
    $login_page_arg = array(
        'post_type'     => 'page',
        'post_title'    => 'Generic Login',
        'post_name'     => 'generic-login',
        'post_status'   => 'publish',
        'post_author'   => 1
    );
    
    $gl_pg_exists = 0;
    $gl_page_id = '';
    $pages = get_pages();

    // Check if 'Generic Login' page already exists
    foreach ($pages as $page) {
        switch ($page->post_name) {
            case "generic-login" :
                $gl_pg_exists = 1;
                update_option(PLUGIN_PREFIX.'gl_page_id', wp2sl_get_ID_by_slug($page->post_name));
                update_option(PLUGIN_PREFIX.'gl_page_slug', $page->post_name);
            break;
        }
    }

    // Generic Login page creation / Page ID storing in db
    if ($gl_pg_exists == 0) {
        $gl_page_id = wp_insert_post($login_page_arg, false);
        update_option(PLUGIN_PREFIX.'gl_page_id', $gl_page_id);
        $pg_data = get_page($gl_page_id);
        update_option(PLUGIN_PREFIX.'gl_page_slug', $pg_data->post_name);
    }
}


/* ========================================================================
 * Login redirection to generic login page
 * ======================================================================== */
function wp2sl_redirect_login_page() {
    global $pagenow;
    if (($pagenow) && $pagenow == "wp-login.php") {
        if ($_SESSION['general_login'] != 1) {
            $gl_page_id = get_option(PLUGIN_PREFIX.'gl_page_id');
            if ($gl_page_id) {
                wp_safe_redirect(get_permalink($gl_page_id));
            }
        }
    }
}


/* ========================================================================
 * Removing login session after logging out
 * ======================================================================== */
function wp2sl_logout_actions() {
    unset($_SESSION['general_login']);
    unset($_SESSION['general_login_id']);
}

/* ======================================================================
 * Plugin Templates Assign
 * ====================================================================== */
function wp2sl_tpl_assign($page_template) {
    // Generic Login page template assign
    $gl_pg_id = get_option(PLUGIN_PREFIX.'gl_page_id');
    $gl_pg_slug = get_option(PLUGIN_PREFIX.'gl_page_slug');
    if (is_page($gl_pg_slug)) {
        $page_template = dirname(__FILE__) . '/templates/tpl_generic_login.php';
    }
    return $page_template;
}


/* ======================================================================
 * Plugin Template Slug
 * ====================================================================== */
function wp2sl_update_page_slug() {
    $pg_id = get_option(PLUGIN_PREFIX.'gl_page_id');
    $pg_data = get_page($pg_id);
    update_option(PLUGIN_PREFIX.'gl_page_slug', $pg_data->post_name);
}


/* ======================================================================
 * Plugin Scripts
 * ====================================================================== */
function wp2sl_js_include() {
    wp_enqueue_script('jquery');
    wp_enqueue_script($handle = 'wp2sl-ajax', $src = plugins_url('js/gl-ajax-actions.js', __FILE__), $deps = array(), $ver = '1.0', $in_footer = FALSE);
}


/* ======================================================================
 * Plugin Scripts - Generic Login Form
 * ====================================================================== */
function wp2sl_form_js_include() {
?>
    <script type="text/javascript" src="<?php echo esc_js(get_bloginfo('url') . '/wp-includes/js/jquery/jquery.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo esc_js(plugins_url('templates/forms/login/js/modernizr.custom.63321.js', __FILE__)); ?>"></script>
    <script type="text/javascript" src="<?php echo esc_js(plugins_url('templates/forms/login/js/custom.js', __FILE__)); ?>"></script>
    <script type="text/javascript" src="<?php echo esc_js(plugins_url('js/gl-ajax-actions.js', __FILE__)); ?>"></script>
<?php
    wp_enqueue_script('jquery');
}


/* ======================================================================
 * Plugin Styles
 * ====================================================================== */
function wp2sl_css_include() {
    /* Register the style handle */
    wp_register_style($handle = 'wp2sl-admin-tpl-css', $src = plugins_url('css/style.css', __FILE__), $deps = array(), $ver = '1.0.0', $media = 'all');
        
    /* Enqueue stylesheet */
    wp_enqueue_style('wp2sl-admin-tpl-css');
}


/* ======================================================================
 * Plugin Styles - Generic Login Form
 * ====================================================================== */
function wp2sl_form_css_include() {
?>
    <link rel="stylesheet" type="text/css" href="<?php echo esc_attr(plugins_url('templates/forms/login/css/style.css', __FILE__)); ?>" />
<?php
}


/* ======================================================================
 * Add jQuery no-conflict in head
 * ====================================================================== */
function wp2sl_add_noconflict() {
?>
<script>
    $ = jQuery.noConflict();
    var myAjax = {"ajaxurl" : "<?php echo esc_js(admin_url('admin-ajax.php')); ?>"};
    var pluginBaseUrl = "<?php echo wp2sl_url(); ?>";
</script>
<?php
}


/* ======================================================================
 * Login page header tags / attributes
 * ====================================================================== */
function wp2sl_tpl_header_html() {
    // Yet to be filled
}

